### ISSUE TITLE
DND still doesn’t turn off automatically when ending screen recording even with new update.

### ISSUE THREAD

**Issue by GTO683** [gilshahar7/DNDMyRecording#4]

**Comment by gilshahar7** [comment]
Yeah i couldnt test it myself, not sure if its something wrong on my end with compiling the code from the pull request.

paging @RuntimeOverflow if you still have time to help us out here :)

**Comment by RuntimeOverflow** [comment]
So I obviously tried it on my device but I also had someone else test it without issues, so clearly there's something weird going on.
Here is my version which I did all the testing with: https://filebin.net/87hd5r2e5oloar2g (If this deb works, something went wrong with merging/compiling.)

**Comment by gilshahar7** [comment]
Awesome
@GTO683, see if this deb file works for you and we will work from there

**Comment by GTO683** [comment]
> Awesome
> @GTO683, see if this deb file works for you and we will work from there

Just tested the .deb file, the issue still remains.

**Comment by RuntimeOverflow** [comment]
Alright back to the drawing board then.

**Comment by GTO683** [comment]
> Alright back to the drawing board then.

I appreciate you.

**Comment by RuntimeOverflow** [comment]
@GTO683 Somewhat different approach: https://filebin.net/87hd5r2e5oloar2g

**Comment by GTO683** [comment]
> @GTO683 Somewhat different approach: https://filebin.net/87hd5r2e5oloar2g

Perfect! You did it!!!

**Comment by RuntimeOverflow** [comment]
Well now it broke for the other guy...

**Comment by GTO683** [comment]
> Well now it broke for the other guy...

What other guy?

**Comment by RuntimeOverflow** [comment]
The one guy I gave it to test before I released the original update.

**Comment by GTO683** [comment]
> The one guy I gave it to test before I released the original update.

Weird.

**Comment by GTO683** [comment]
> The one guy I gave it to test before I released the original update.

Maybe he still has the others installed?

**Comment by GTO683** [comment]
> The one guy I gave it to test before I released the original update.

I had 2 people test the .deb and it worked for them. Were you able to figure out why it broke for him? I’d say its safe to make the pull request if its working on your device.

**Comment by RuntimeOverflow** [comment]
Yes I‘ll try to fix it tonight for him tonight, but I‘ll do the PR anyway if I can‘t fix it he can keep the old version.

**Comment by GTO683** [comment]
> Yes I‘ll try to fix it tonight for him tonight, but I‘ll do the PR anyway if I can‘t fix it he can keep the old version.

Cool. Thx again.

**Comment by ghost** [comment]
> @GTO683 Somewhat different approach: https://filebin.net/87hd5r2e5oloar2g

It's working!!!!

The DND switch must be added to the control center.

Thanks.

**Comment by RuntimeOverflow** [comment]
> The DND switch must be added to the control center.

Blame @gilshahar7 for that ;), I think his implementation needs the CC because he toggles it by pretending to be the CC.

**Comment by gilshahar7** [comment]
lol I'm blaming rpetrich for that: https://github.com/a3tweaks/Flipswitch/blob/c1fe70e25d843c1c55b1df954b256ca5850910af/Switches/DoNotDisturb.x#L25
